### ISSUE TITLE
Topic is not automatically created when I use table.whitelist configuration

### ISSUE THREAD

**Issue by shenzgang** [m0rph2us/m0rph2us.github.io#13]
hello！
Problem description:
When I was in the connector.Properties configuration property table.whitelist, I did not see the topic automatically created; when it was not configured, it was automatically created. How do I configure table data to be written to the corresponding Topic?
My version information is as follows:
Kafka:  2.11_1.1.0
Debezium: 0.9.5
Mysql: 5.7
my connector.properties:
name=debezium-connector-mysql
connector.class=io.debezium.connector.mysql.MySqlConnector
slot.name=debezium
database.hostname=192.168.219.129
database.port=3306
database.user=root
database.password=123456
database.whitelist=test
table.whitelist=table
database.server.id=123456789
database.server.name=full  
database.history.kafka.bootstrap.servers=node-01:9092,node-02:9092,node-03:9092
database.history.kafka.topic=mysql_topic
include.schema.changes=true
database.history.skip.unparseable.ddl=true
transforms=unwrap,changetopic
transforms.unwrap.type=io.debezium.transforms.UnwrapFromEnvelope
transforms.changetopic.type=org.apache.kafka.connect.transforms.RegexRouter
transforms.changetopic.regex=(.*)
transforms.changetopic.replacement=$1

**Comment by m0rph2us** [comment]
Hi

Debezium document said:

```
An optional comma-separated list of regular expressions that match fully-qualified table identifiers for tables to be monitored; any table not included in the whitelist will be excluded from monitoring. Each identifier is of the form databaseName.tableName. By default the connector will monitor every non-system table in each monitored database. May not be used with table.blacklist.
```

So, you would give a try to use fully qualified table name in the table.whitelist. For example, if you have a database named TEST and table named MY_TABLE. You can put a table like TEST.MY_TABLE in that white list.

Hope this helps you. Thanks.

**Comment by shenzgang** [comment]
thank you very much! this problem has been solved according to your prompt!

**Comment by shenzgang** [comment]
hello，Why can only listen to the new and modified events of the database? When I delete a data, Topic does not see the change information of the event. How can I control the event I want to listen to?

**Comment by m0rph2us** [comment]
Hmm.. I have no idea if you can not see any delete event.

Check document: https://debezium.io/documentation/reference/1.2/connectors/mysql.html#_delete_change_event_value

And my example: https://github.com/m0rph2us/docker-debezium

And you can join gitter channel for debezium: https://gitter.im/debezium/user
