### ISSUE TITLE
In cluster mode, debezium connect to mysql configuration databane.whitelist and Table.whitelist not exist at the same time?

### ISSUE THREAD

**Issue by shenzgang** [m0rph2us/m0rph2us.github.io#14]
Hello, In cluster mode, debezium connect to mysql configuration databane.whitelist and Table.whitelist not exist at the same time?
When I use the standalone schema, I can listen to the tables I select by configuring database.whitelist and table.whitelist properties in Properties, and it works fine. But when I switched to cluster mode and configured it in JSON format, I couldn't listen to the library table I chose, and I tested that both configurations didn't exist at the same time. How do I configure json properties to listen to the tables I select?
My cluster configuration:
{
  "name": "debezium-connector-mysql",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "node-01",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "123456",
    "database.server.id": "12345678",
    "database.server.name": "full",
    "database.whitelist": "test",
    "table.whitelist":"test.aaa,test.bbb",
    "database.history.store.only.monitored.tables.ddl":true,
    "database.history.kafka.bootstrap.servers": "node-01:9092,node-02:9092,node-03:9092",
    "database.history.kafka.topic": "mysql_history_topic",
    "database.history.skip.unparseable.ddl":"true",
    "include.schema.changes": "true",
    "transforms":"unwrap,changetopic",
    "transforms.unwrap.type":"io.debezium.transforms.UnwrapFromEnvelope",
    "transforms.changetopic.type":"org.apache.kafka.connect.transforms.RegexRouter",
    "transforms.changetopic.regex":"(.*)",
    "transforms.changetopic.replacement":"$1-smt"
  }
}
I can configure Database.whitelist and table.blacklist to listen to a given table, but if I have fewer tables to listen to, I need to configure more table.blacklist. What better way?

**Comment by m0rph2us** [comment]
Hi :)
If you are referring to "MySQL Cluster", As Debezium is just a replication client, so you won't be use like that. In other words, you need to attach your Debezium to a single MySQL node.
I hope this helps you.

**Comment by shenzgang** [comment]
If I update the configuration and add a new table to table.whitelist, how do I get all the data for this table instead of starting from the binlog?

**Comment by m0rph2us** [comment]
If you update configuration, then Debezium will do snapshot for the new table.(But I didn't test. This is just my opinion).

Although Debezium have snapshot capability, I usually use a separate ETL application for data initializing. It is more flexible than using built-in snapshot capability.
